version: '3.7'
networks:
  skeleton: null
services:
  nginx:
    image: 'nginx:latest'
    container_name: 'news-nginx'
    working_dir: /application
    depends_on:
      - php-fpm
      - mysql
    volumes:
      - '.:/application'
      - './docker/nginx/logs:/var/log/nginx'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8000:80'
    networks:
      skeleton: null

  php-fpm:
    build: ./docker
    container_name: 'news-phpfpm'
    working_dir: /application
    tty: true
    volumes:
      - '.:/application'
      - './docker/php/logs/errors.log:/var/log/php-fpm/errors.log'
    networks:
      skeleton: null

  mysql:
    image: 'mysql:latest'
    container_name: 'news-mysql'
    working_dir: /application
    tty: true
    volumes:
      - '.:/application'
      - './docker/mysql/mysql-data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: 'newsparser'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3307:3306'
    restart: always
    networks:
      skeleton: null
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin
    container_name: 'news-phpmyadmin'
    depends_on:
      - mysql
    environment:
      PMA_HOST: 'news-mysql'
    ports:
      - '5000:80'
    tty: false
    networks:
      skeleton: null

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  db-data: null
###> doctrine/doctrine-bundle ###
